<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = [
            [
                'id_model' => 7,
                'nama_model' => 'Afia Khansa Rafani',
                'city' => 'Bogor,  Jawa Barat',
                'age' => 11,
                'height' => 160,
                'weight' => 40,
                'shoes_size' => 38,
                'bust' => 73,
                'waist' => 65,
                'size' => 'xs',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/NJP5dJwA7L504LSMlFVuf1FqDBzvpgykXYKfEKp8.png',
                'experience_value' => 1,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 8,
                'nama_model' => 'Camilla Aleecea',
                'city' => 'Bekasi,  Jawa Barat',
                'age' => 15,
                'height' => 166,
                'weight' => 50,
                'shoes_size' => 39,
                'bust' => 78,
                'waist' => 63,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/z9gftwpEXuv9ojtpMPg8iel51R2LF4Yhpw85ktFC.png',
                'experience_value' => null,
                'experience_unit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 9,
                'nama_model' => 'Violla Alexandria Kirana',
                'city' => 'Jakarta, DKI Jakarta',
                'age' => 10,
                'height' => 141,
                'weight' => 37,
                'shoes_size' => 37,
                'bust' => 73,
                'waist' => 67,
                'size' => 'S',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/LCJzL3AXmh4C3xIxlPLHq8PJWoLwVKrv3XQzuMeJ.png',
                'experience_value' => null,
                'experience_unit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 10,
                'nama_model' => 'Clarissa Cheryl Steyz',
                'city' => 'Tangerang, Banten',
                'age' => 6,
                'height' => 121,
                'weight' => 23,
                'shoes_size' => 30,
                'bust' => 65,
                'waist' => 60,
                'size' => 'M',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/SHrZwa6lrR2COlOwElJPq0A0GsLrvFFBIVmZiKhJ.png',
                'experience_value' => 6,
                'experience_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 11,
                'nama_model' => 'Nathania Raynelle Wijaya',
                'city' => 'Jakarta, DKI Jakarta',
                'age' => 9,
                'height' => 145,
                'weight' => 39,
                'shoes_size' => 39,
                'bust' => 76,
                'waist' => 70,
                'size' => 'XL',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754676169_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 4,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 12,
                'nama_model' => 'Nikita Wilmer Chung Steyz',
                'city' => 'Tangerang, Banten',
                'age' => 12,
                'height' => 121,
                'weight' => 23,
                'shoes_size' => 30,
                'bust' => 65,
                'waist' => 60,
                'size' => 'M',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754676291_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 3,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 13,
                'nama_model' => 'Michelle Fidellia Parinussa',
                'city' => 'Bogor, Jawa Barat',
                'age' => 11,
                'height' => 145,
                'weight' => 43,
                'shoes_size' => 38,
                'bust' => 80,
                'waist' => 72,
                'size' => 'S',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754676439_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 2,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 14,
                'nama_model' => 'Kalyca Lashira',
                'city' => 'Tangerang, Banten',
                'age' => 6,
                'height' => 121,
                'weight' => 23,
                'shoes_size' => 30,
                'bust' => 65,
                'waist' => 60,
                'size' => 'M',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754676966_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 3,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 15,
                'nama_model' => 'Chevazrilia Alfaruk',
                'city' => 'Bekasi, Jawa Barat',
                'age' => 11,
                'height' => 149,
                'weight' => 35,
                'shoes_size' => 37,
                'bust' => 82,
                'waist' => 88,
                'size' => 'S',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754676584_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 1,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 16,
                'nama_model' => 'Aleeya Shafiyah',
                'city' => 'Jakarta, DKI Jakarta',
                'age' => 11,
                'height' => 147,
                'weight' => 35,
                'shoes_size' => 38,
                'bust' => 72,
                'waist' => 60,
                'size' => 'M',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754677198_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 3,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 17,
                'nama_model' => 'Alisha Ahri',
                'city' => 'Tangerang, Banten',
                'age' => 5,
                'height' => 121,
                'weight' => 23,
                'shoes_size' => 30,
                'bust' => 65,
                'waist' => 60,
                'size' => 'M',
                'categories' => 'kids',
                'status' => 'available',
                'photo' => 'photos/1754677083_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 3,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 18,
                'nama_model' => 'Nazwa Audina',
                'city' => 'Jakarta Timur, Jakarta',
                'age' => 21,
                'height' => 166,
                'weight' => 52,
                'shoes_size' => 39,
                'bust' => 90,
                'waist' => 72,
                'size' => 'M',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754675880_WhatsApp Image 2025-05-07 at 15.59.31_e3aafd82.png',
                'experience_value' => 4,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 19,
                'nama_model' => 'Rara Dharmawan',
                'city' => 'Depok, Jawa Barat',
                'age' => 25,
                'height' => 170,
                'weight' => 48,
                'shoes_size' => 39,
                'bust' => 87,
                'waist' => 74,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754677322_WhatsApp Image 2025-05-07 at 15.59.46_2d4dccdc.png',
                'experience_value' => 10,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 20,
                'nama_model' => 'Kyna',
                'city' => 'Depok, Jawa Barat',
                'age' => 17,
                'height' => 170,
                'weight' => 48,
                'shoes_size' => 39,
                'bust' => 87,
                'waist' => 74,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754677552_WhatsApp Image 2025-05-07 at 15.59.43_473e5d58.png',
                'experience_value' => 2,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 21,
                'nama_model' => 'Putri Nailah Azzahra',
                'city' => 'Bogor, Jawa Barat',
                'age' => 19,
                'height' => 165,
                'weight' => 47,
                'shoes_size' => 39,
                'bust' => 91,
                'waist' => 68,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754677464_WhatsApp Image 2025-05-07 at 15.59.46_2d4dccdc.png',
                'experience_value' => 12,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 22,
                'nama_model' => 'Dini Aura',
                'city' => 'Depok, Jawa Barat',
                'age' => 16,
                'height' => 170,
                'weight' => 48,
                'shoes_size' => 39,
                'bust' => 87,
                'waist' => 74,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754678074_WhatsApp Image 2025-05-07 at 15.59.43_473e5d58.png',
                'experience_value' => 2,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 23,
                'nama_model' => 'Kirana Khanza Aurelia',
                'city' => 'Bogor, Jawa Barat',
                'age' => 11,
                'height' => 157,
                'weight' => 39,
                'shoes_size' => 39,
                'bust' => 74,
                'waist' => 64,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754677650_WhatsApp Image 2025-05-07 at 15.59.44_5805b87c.png',
                'experience_value' => 2,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 24,
                'nama_model' => 'Maya Amjad',
                'city' => 'Depok, Jawa Barat',
                'age' => 11,
                'height' => 170,
                'weight' => 48,
                'shoes_size' => 39,
                'bust' => 87,
                'waist' => 74,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754678469_WhatsApp Image 2025-05-07 at 15.59.44_5805b87c.png',
                'experience_value' => 2,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 25,
                'nama_model' => 'Najwa Madina Azzahra',
                'city' => 'Bogor, Jawa Barat',
                'age' => 12,
                'height' => 152,
                'weight' => 40,
                'shoes_size' => 38,
                'bust' => 74,
                'waist' => 75,
                'size' => 'XS',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754678213_WhatsApp Image 2025-05-07 at 15.59.44_5805b87c.png',
                'experience_value' => 3,
                'experience_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 26,
                'nama_model' => 'Fathia Riyandita Anwari',
                'city' => 'Bogor, Jawa Barat',
                'age' => 11,
                'height' => 161,
                'weight' => 48,
                'shoes_size' => 39,
                'bust' => 94,
                'waist' => 67,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754678687_WhatsApp Image 2025-05-07 at 15.59.46_2d4dccdc.png',
                'experience_value' => 2,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 27,
                'nama_model' => 'Caren Magdalena Praselia',
                'city' => 'Jakarta, DKI Jakarta',
                'age' => 15,
                'height' => 163,
                'weight' => 52,
                'shoes_size' => 40,
                'bust' => 85,
                'waist' => 74,
                'size' => 'S',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754678817_WhatsApp Image 2025-05-07 at 15.59.44_5805b87c.png',
                'experience_value' => 10,
                'experience_unit' => 'years',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_model' => 28,
                'nama_model' => 'Sabrina Andhita Alkaf',
                'city' => 'Jakarta, DKI Jakarta',
                'age' => 15,
                'height' => 165,
                'weight' => 52,
                'shoes_size' => 40,
                'bust' => 88,
                'waist' => 72,
                'size' => 'M',
                'categories' => 'teens',
                'status' => 'available',
                'photo' => 'photos/1754678568_WhatsApp Image 2025-06-20 at 23.00.26_4d2df451.png',
                'experience_value' => 6,
                'experience_unit' => 'months',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('models')->insert($models);
    }
}
