<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'id_user' => 1,
                'name' => 'admin',
                'email' => 'admin@a',
                'password' => '$2y$12$AsFkkODzpY5wAqRUsVzADugUf/CRq3NIhZhFdbTMsmS.2EnpCy0FW',
                'number_phone' => '0987654321',
                'pin' => null,
                'is_verified' => 1,
                'role' => 'admin',
                'remember_token' => 'Ftm0rYsGkV3YKvC35VBIZmEsWRVc0DnsZxdUGd76g7w9kranQ6qQoi78MbW4',
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 15,
                'name' => 'Faiz Firstian Nugroho',
                'email' => 'nugrohofaiz99@gmail.com',
                'password' => '$2y$12$JMIBlX7u9RwLkeEhOf2XuOW.7C.MqD/Yj7jQa1EXVUE03laYaMX2i',
                'number_phone' => '089793592667',
                'pin' => null,
                'is_verified' => 0,
                'role' => 'client',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 16,
                'name' => 'sscscscsc',
                'email' => 'superkyross@gmail.com',
                'password' => '$2y$12$eRswSvkmaA4x9iSRBE6Wq.fW0y4M6BiKryvWaYjEMbCOCdFm9Rhn6',
                'number_phone' => '08979359266',
                'pin' => null,
                'is_verified' => 0,
                'role' => 'client',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 17,
                'name' => 'Rofief Amanulloh',
                'email' => '2210511061@mahasiswa.upnvj.ac.id',
                'password' => '$2y$12$3mntokQZqFbejLAvMQR3ZOjLYQlcVXOXohgXuQVgOD2ddAIZzN/oO',
                'number_phone' => null,
                'pin' => null,
                'is_verified' => 0,
                'role' => 'client',
                'remember_token' => null,
                'last_active' => '2025-08-05 20:34:59',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 18,
                'name' => 'Rofief Amanulloh',
                'email' => 'rofiefamanulloh4@gmail.com',
                'password' => '$2y$12$Vvn4yDBLUoAw0v6JHqAtbe2QKzQj9TePb.YJgkiFpef3xebM0n/RS',
                'number_phone' => '082213819145',
                'pin' => null,
                'is_verified' => 0,
                'role' => 'client',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 19,
                'name' => 'rofief amanulloh',
                'email' => 'amanullohrofief@gmail.com',
                'password' => '$2y$12$LPeX1Hnk5u6wlMcx9Ycd3u6jtku3Cno4CPr5PRo2NIjnb4gqOl0ee',
                'number_phone' => '082213819145',
                'pin' => null,
                'is_verified' => 1,
                'role' => 'client',
                'remember_token' => null,
                'last_active' => '2025-08-05 21:21:01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 20,
                'name' => 'Afia Khansa Rafani',
                'email' => null,
                'password' => '$2y$12$hwFF2vQ7SFak.RL0bo83VeWliU5lO0kEZ9qgaS3miRuWNWkeDCoYu',
                'number_phone' => null,
                'pin' => '205572',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 21,
                'name' => 'Camilla Aleecea',
                'email' => null,
                'password' => '$2y$12$/a3z5ErUyurYvhfyHn0SIOK.oz2Y5JCNCEOi6hxJGC260z1KiX/72',
                'number_phone' => null,
                'pin' => '404102',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 22,
                'name' => 'Violla Alexandria Kirana',
                'email' => null,
                'password' => '$2y$12$Mj349kXQF2k84re.SCCrYedPF2WQDaZyd5hFmD1OGLST3piNGuudW',
                'number_phone' => null,
                'pin' => '484084',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 23,
                'name' => 'Clarissa Cheryl Steyz',
                'email' => null,
                'password' => '$2y$12$mvrwO6VCLWO6ouZOnD7yLuJgzcoCkj83984WixlItj/o1fH1hjChO',
                'number_phone' => null,
                'pin' => '260185',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 24,
                'name' => 'Nathania Raynelle Wijaya',
                'email' => null,
                'password' => '$2y$12$mMqHddDGJsjiq0iqQFFKDu8sBbRzjliV.qepdQQQxWMEPopzmOdUG',
                'number_phone' => null,
                'pin' => '642675',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 25,
                'name' => 'Nikita Wilmer Chung Steyz',
                'email' => null,
                'password' => '$2y$12$eCxUrOud6sItN25EP8N6Ouxg2RLGMwrSGdAjHq3/QBLvWqUkLrjWG',
                'number_phone' => null,
                'pin' => '658259',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 26,
                'name' => 'Michelle Fidellia Parinussa',
                'email' => null,
                'password' => '$2y$12$LTHVNScGLv90X7Cth3JZ9.SwZcEgslRBu31fMqy0BQ.rCoEzGpSk.',
                'number_phone' => null,
                'pin' => '902311',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 27,
                'name' => 'Kalyca Lashira',
                'email' => null,
                'password' => '$2y$12$1xMgKHeNdNoe5T1wSD6D/OZTZ48.gkih7e0wqMK/l6wQlXHwqMitq',
                'number_phone' => null,
                'pin' => '450422',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 28,
                'name' => 'Chevazrilia Alfaruk',
                'email' => null,
                'password' => '$2y$12$brMF.xQP3YCHFKsBJGUhsObyCCuO8h2zxUAL66.ZbFHbTzM/3.3dC',
                'number_phone' => null,
                'pin' => '033470',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 29,
                'name' => 'Aleeya Shafiyah',
                'email' => null,
                'password' => '$2y$12$fiV7aTfqhA7uEyZLkJ8Koe0ZHvSYEk24EWpe25.cooYflbTM1y87C',
                'number_phone' => null,
                'pin' => '322121',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 30,
                'name' => 'Alisha Ahri',
                'email' => null,
                'password' => '$2y$12$caLyJMnjoSramJWM23hd3OPDreSzzM9UUKDRUxXK4OflLM0peGJOi',
                'number_phone' => null,
                'pin' => '471121',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 31,
                'name' => 'Nazwa Audina',
                'email' => 'nazwa@gmail.com',
                'password' => '$2y$12$4wFg0vEJMRUyNatfCCmCHef8VzkE3jCiQ0Q/vsRz73zqQS6eSTKqu',
                'number_phone' => '082213819145',
                'pin' => '841979',
                'is_verified' => 1,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => '2025-08-18 23:09:47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 32,
                'name' => 'Rara Dharmawan',
                'email' => null,
                'password' => '$2y$12$C4NO7FcJ45ZGGBknVI0HZ.VkjlXXYlUk1TWLftmQMDn06pLwPiI4K',
                'number_phone' => null,
                'pin' => '744333',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 33,
                'name' => 'Kyna',
                'email' => null,
                'password' => '$2y$12$st92Zm2LKC9X/wtyE2L6vePiogCwHeLnROrkZgOI4jbgQuOzjyk7O',
                'number_phone' => null,
                'pin' => '088141',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 34,
                'name' => 'Putri Nailah Azzahra',
                'email' => null,
                'password' => '$2y$12$ofW1homFKxdaMY4vvoEqHuoNBIaQSKXKlZZEbleMIchHqOY7QbHk6',
                'number_phone' => null,
                'pin' => '086448',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 35,
                'name' => 'Dini Aura',
                'email' => null,
                'password' => '$2y$12$HVkZmQGp6Nm2Ac9hi4P9/.TUHfEUxXyoT3uiTwbs5.zFx27OGGlxq',
                'number_phone' => null,
                'pin' => '522942',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 36,
                'name' => 'Kirana Khanza Aurelia',
                'email' => null,
                'password' => '$2y$12$93ou8yoetNZGEX56TBSVi.ESaasobFiPqX1Fg2dD0JyX3o2wpEfDG',
                'number_phone' => null,
                'pin' => '810276',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 37,
                'name' => 'Maya Amjad',
                'email' => null,
                'password' => '$2y$12$Yky5whOfNm8Uu//3OpU/XeEgKKl9ajgBQCsNfht1C412j0r1dza/S',
                'number_phone' => null,
                'pin' => '736120',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 38,
                'name' => 'Najwa Madina Azzahra',
                'email' => null,
                'password' => '$2y$12$FyJz/5j26Ev2KdQfQuLQxOR6pvZXqaDq.5/iFL.Uyhosq256xwFUG',
                'number_phone' => null,
                'pin' => '793083',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 39,
                'name' => 'Fathia Riyandita Anwari',
                'email' => null,
                'password' => '$2y$12$RldzZKmopZxvqYBaV69PM.3r8ICzBsNfq4qVhgmHFStgKDAB7g4SC',
                'number_phone' => null,
                'pin' => '781882',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 40,
                'name' => 'Caren Magdalena Praselia',
                'email' => null,
                'password' => '$2y$12$2bbadRNtFQdAVvzmUcaAP.imWqFSj2GHEGpDlwCUO7LGOlk1ZOAvO',
                'number_phone' => null,
                'pin' => '095271',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 41,
                'name' => 'Sabrina Andhita Alkaf',
                'email' => null,
                'password' => '$2y$12$C0DTnW0aGMIpzXYz9Y6.f.C0hSBky5dFMc7O05LwKbNHuI2jMdoM2',
                'number_phone' => null,
                'pin' => '116004',
                'is_verified' => 0,
                'role' => 'model',
                'remember_token' => null,
                'last_active' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 48,
                'name' => 'Faiz Firstian Nugroho',
                'email' => 'nugrohofaiz28@gmail.com',
                'password' => '$2y$12$5.bqyQmMOv8Ps3pBKdphNuDvM/vu00bVeP5IX4HdrJ2wPxXg9glVK',
                'number_phone' => '08979359266',
                'pin' => null,
                'is_verified' => 1,
                'role' => 'client',
                'remember_token' => null,
                'last_active' => '2025-08-21 22:21:26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
